"""Curated upper-body wardrobes used by the 500-performer production catalog."""

WARDROBE_GROUPS = {
    "sensual contemporary": {
        "relaxed plain cotton tee": "dusty-rose fitted cotton tee with a low scoop neckline",
        "double-breasted blazer over slim trousers": "camel close-fitting sleeveless square-neck knit top",
        "fitted long-sleeve henley with denim shorts": "fitted deep-teal off-the-shoulder cashmere sweater",
        "fitted ribbed turtleneck with skinny jeans and ankle boots": "fitted ivory ribbed top with an asymmetric neckline",
        "lightweight zip hoodie over a fitted tank top": "close-fitting champagne satin corset dress with a structured sweetheart neckline and narrow shoulder straps",
        "velvet off-the-shoulder gown with opera gloves and a statement necklace": "fitted cherry-red ribbed scoop-neck top",
        "one-shoulder gown with a metallic belt and elegant updo": "close-fitting dark-wine satin one-shoulder cocktail dress with soft draping",
        "fitted cardigan buttoned as a top with jeans": "fitted petrol-blue square-neck bodysuit with smooth satin paneling",
        "studded blazer over a fitted camisole": "charcoal fitted satin camisole with a low square neckline",
        "velvet blazer over a fitted top and leather skirt": "fitted deep-plum wrap top with a low V neckline",
        "simple bandeau top under a lightweight cropped cardigan": "ivory satin camisole under a soft black cardigan",
        "cropped blazer with a fitted dress": "fitted dark-petrol long-sleeve jersey top with gathered ruching",
        "soft fitted turtleneck with a leather skirt": "one-shoulder champagne satin top",
        "velvet gown with long sleeves and classic Hollywood styling": "close-fitting burgundy velvet dress with a sculpted portrait neckline",
        "luxury satin jumpsuit with a dramatic cape": "rich indigo close-fitting satin halter jumpsuit with an open back",
        "sophisticated velvet jumpsuit": "open-collar ivory silk blouse",
        "fitted crop top with a flowing maxi skirt": "fitted pale-lilac fine-knit top with a wide boat neckline",
        "structured blazer with leather shorts": "fitted forest-green square-neck long-sleeve top",
        "fitted sleeveless polo knit": "deep-teal cowl-neck silk shell",
        "high-waisted midi skirt with a tucked-in blouse": "fitted cherry-red scoop-neck bodysuit",
        "eyelet sundress": "fitted plum off-the-shoulder jersey top",
        "business suit with minimalist jewelry": "fitted cream mock-neck top",
        "casual wrap dress with a moderate V neckline": "close-fitting midnight-blue satin wrap dress with a low V neckline",
        "fitted athletic tank top": "fitted ruby-red soft V-neck knit top",
        "layered long-sleeve striped shirt under a graphic T-shirt": "fitted cool-white cotton top with a portrait neckline",
        "button-front shirt dress with a belt": "close-fitting cherry-red satin shirt dress with a sharp open collar",
        "tank top with cargo pants and fingerless gloves": "fitted black one-shoulder ribbed cotton top",
        "satin slip dress with high heels": "ivory fitted wrap-front silk top",
        "overall dress over a striped shirt": "fitted petrol-blue square-neck bodysuit",
        "modern asymmetric evening dress": "fitted charcoal cold-shoulder jersey top",
        "cable-knit sweater with leather leggings": "crimson satin blouse with an open collar",
        "breezy patterned kimono over a swimsuit": "pale-lilac satin cowl-neck top",
        "fitted blazer with a pencil skirt": "moss close-fitting sleeveless wrap top with a low V neckline",
        "cropped cable-knit sweater with wide-leg pants": "fitted black bodysuit with a small keyhole neckline",
        "elegant silk gown with minimal jewelry and refined styling": "cool-white silk halter shell",
        "modern asymmetrical evening gown with statement earrings": "fitted magenta ribbed scoop-neck top",
        "corset top with leather pants and chunky platform boots": "steel-gray off-the-shoulder fine-knit top",
        "long peacoat over a coordinated outfit": "ivory silk blouse with translucent organza shoulders",
        "casual floral sundress with a moderate square neckline": "dark-wine gathered wrap top",
        "oversized flannel shirt over a fitted tank and jean shorts": "fitted teal top with a portrait neckline",
        "casual scoop-neck knit top": "silver-gray asymmetric satin shell",
        "distressed denim jacket covered": "cherry-red silk halter blouse with gathered shoulders",
        "dark ripped jeans with a fitted turtleneck and leather jacket": "burgundy close-fitting sleeveless mock-neck top",
        "casual draped jersey top with a modest neckline": "rich plum close-fitting off-shoulder jersey top",
        "off-shoulder cotton dress": "dusty-rose close-fitting cotton dress with a low square neckline and narrow shoulder straps",
        "casual sleeveless button-front blouse": "moss fitted satin halter top",
    },
    "dark glam": {
        "chic jumpsuit with a waist belt and heels": "close-fitting deep-emerald velvet halter jumpsuit with a sculpted neckline",
        "silk blouse tucked into tailored trousers with pointed heels": "black satin cowl-neck camisole with silver chain straps",
        "tie-front blouse with jeans": "close-fitting midnight-blue satin one-shoulder bodysuit with sculpted ruching",
        "ribbed scoop-neck tank top": "fitted oxblood velvet wrap top",
        "satin slip dress": "close-fitting midnight-blue liquid-satin slip dress with a portrait neckline",
        "hoodie with a pleated plaid skirt and fishnet sleeves": "black liquid-satin halter top",
        "floor-length satin evening gown with a thigh-high slit, elegant stilettos, and diamond earrings": "close-fitting deep-wine velvet evening dress with a wide portrait neckline",
        "ribbed sweater with dark denim and Chelsea boots": "gunmetal metallic-knit top with an asymmetric neckline",
        "fine-knit short-sleeve sweater": "fitted black jersey top with a collarbone cutout",
        "cropped zip hoodie with a cargo skirt and sneakers": "fitted plum satin blouse with an open neckline",
        "wrap sweater with slim trousers": "black draped evening top with a soft sheen",
        "linen shorts with a sleeveless blouse": "fitted crimson velvet top with subtle ruching",
        "short-sleeve knitted polo top": "black sculptural satin top with a folded neckline",
        "soft gathered peasant blouse": "fitted charcoal off-the-shoulder velvet sweater",
        "smart blouse tucked into a pleated midi skirt": "deep-emerald satin wrap blouse",
        "luxurious satin evening dress": "close-fitting petrol-blue satin evening dress with sheer upper paneling",
        "soft cashmere sweater tucked into a satin skirt": "fitted charcoal velvet top with a square neckline",
        "sophisticated sheath dress with classic heels": "oxblood satin cowl-neck shell",
        "relaxed plaid shirt over a fitted crop top": "gunmetal velvet top with a keyhole neckline",
        "square-neck ribbed knit top": "fitted black burnout-velvet top with an asymmetric neckline",
        "draped boat-neck top": "crimson liquid-satin one-shoulder top",
        "knit short-sleeve sweater with ankle-length jeans": "dark-wine crushed-velvet scoop-neck top",
        "casual short-sleeve jersey top with a moderate scoop neckline": "black sequined top with a portrait neckline",
        "sleeveless ribbed tank top": "petrol-blue velvet off-the-shoulder top",
        "soft jersey top with a modest V neckline": "silver metallic-knit cowl-neck top",
        "modern gothic-inspired fitted dress with subtle lace accents": "fitted black satin twist-front top",
        "casual short-sleeve jersey top": "cherry-red velvet top with a portrait neckline",
        "fitted polo shirt with a pleated tennis skirt": "midnight-blue satin blouse with a sharp open collar",
        "satin halter gown with a sleek ponytail": "fitted black velvet top with a folded portrait neckline",
        "casual dark denim shirt with the collar open": "gunmetal sequined top with a square neckline",
        "wrap knit top with skinny jeans": "black draped velvet top with a wide boat neckline",
        "sheer mesh blouse over a camisole with tailored trousers": "deep-emerald velvet top with corset-inspired seams",
        "graphic hoodie over denim shorts with striped knee socks": "charcoal satin halter top with minimalist hardware",
        "fitted evening gown with a dramatic train and high heels": "close-fitting dark-plum satin evening dress with a sculptural folded neckline",
        "faux-fur jacket over a fitted dress": "deep-burgundy close-fitting velvet dress with a low square neckline",
    },
    "romantic goth": {
        "oversized hoodie with loose cargo pants and skate shoes": "fitted black lace top with an illusion sweetheart neckline",
        "cropped hoodie with yoga leggings and athletic sneakers": "black velvet corset-inspired top",
        "blouse with a fitted blazer": "black chiffon blouse with a high lace collar",
        "sleeveless tank with ripped jeans and layered necklaces": "oxblood velvet off-the-shoulder top with black lace trim",
        "fitted square-neck long-sleeve top": "fitted plum burnout-velvet blouse",
        "lace-trim camisole with fitted jeans and heels": "black satin blouse with a lace-up front",
        "silk camisole with tailored pants": "deep-wine jacquard top with an ornate square neckline",
        "metallic evening gown": "close-fitting raven-black lace evening dress with a high illusion neckline",
        "linen button-up shirt tied at the waist with wide-leg trousers and leather sandals": "ivory Victorian lace blouse with black ribbon detailing",
        "wrap dress with ankle boots": "close-fitting black velvet wrap dress with a dramatic lace-trimmed neckline",
        "wrap dress with delicate accessories": "fitted dark-aubergine brocade dress with corset-inspired seams",
        "mesh long-sleeve top layered under a graphic T-shirt with ripped jeans": "black sheer lace sleeves over an opaque fitted bodice",
        "structured blazer over a fitted turtleneck": "raven-black lace bodice with a high illusion neckline",
        "sleeveless mock-neck knit top": "black embroidered blouse with sheer shoulders",
        "oversized striped sweater with a pleated plaid skirt and canvas sneakers": "plum velvet top with a gothic open neckline",
        "cropped leather jacket with tartan pants and combat boots": "fitted black romantic blouse with ruffled trim",
        "fitted turtleneck with a leather pencil skirt and knee-high boots": "dark-wine lace blouse with a portrait neckline",
        "simple fitted crew-neck tee": "black velvet top with an illusion square neckline",
        "vintage hoodie with distressed jeans": "fitted oxblood brocade top with corset-inspired seams",
        "denim vest with pins, ripped shorts, and tall boots": "black chiffon blouse with a lace-trimmed keyhole neckline",
        "graphic crop top with plaid trousers and a studded belt": "deep-plum velvet bodice with sheer lace shoulders",
        "leather jacket with trousers": "ivory organza blouse with a black velvet ribbon collar",
        "denim overalls with platform sneakers": "black jacquard top with an ornate sweetheart neckline",
        "lightweight knit top with a pleated skirt": "fitted aubergine lace top with long sheer sleeves",
        "soft off-shoulder sweater": "oxblood satin blouse with a high lace yoke",
        "cozy off-shoulder sweater with a plaid mini skirt, knee-high socks, and ankle boots": "black burnout-velvet blouse with gathered shoulders",
        "soft jersey sundress with a moderate scoop neckline": "close-fitting deep-wine jersey dress with a lace-up scoop neckline",
        "cropped fitted cardigan with straight-leg jeans": "raven-black velvet top with a sculpted portrait neckline",
    },
    "punk / grunge / alt": {
        "linen midi dress with espadrilles": "cropped black leather jacket over a fitted ribbed tank",
        "vintage graphic T-shirt with an oversized denim jacket and baggy jeans": "charcoal close-fitting graphic T-shirt with muted-rust print and a low scoop neckline",
        "tie-dye hoodie with ripped jeans and skate shoes": "solid muted-plum close-fitting zip hoodie",
        "fitted tank top with linen shorts": "distressed charcoal denim jacket over a fitted mesh top",
        "sequined mini dress with stilettos": "close-fitting crimson sequined cocktail dress with an asymmetric neckline and layered silver chains",
        "relaxed crew-neck sweatshirt": "forest close-fitting cropped sweatshirt with a wide scoop neckline",
        "figure-hugging velvet dress": "close-fitting deep-wine ribbed-knit dress with an off-the-shoulder neckline",
        "jumpsuit with accessories": "fitted oxblood henley with metal eyelet detailing",
        "oversized rugby shirt with baggy jeans": "burgundy-and-cream close-fitting rugby top with a deep open collar",
        "tailored blazer with trousers": "fitted deep-petrol scoop-neck top under a cropped oxblood moto jacket",
        "cocktail dress with metallic heels": "black mesh long-sleeve top over a fitted camisole",
        "soft oversized knit sweater with high-waisted skinny jeans and sneakers": "fitted black ribbed tank with harness-inspired straps",
        "soft V-neck cotton tee": "cropped oxblood moto jacket over a black bodysuit",
        "blazer over a fitted knit top": "close-fitting charcoal band tee with a wide neckline",
        "fitted V-neck T-shirt with high-waisted jeans and sneakers": "fitted black-and-crimson striped knit top",
        "oversized scarf with a tailored coat and slim jeans": "cropped black cardigan worn open over a fitted camisole with layered chains",
        "casual crew-neck ribbed knit top": "distressed black knit sweater with a wide neckline",
        "bodycon midi dress with elegant heels": "close-fitting oxblood leather-look dress beneath a black denim vest with silver pins",
        "satin camisole under an open blazer with slim trousers": "washed-black long-sleeve thermal with an open collar",
        "asymmetrical-neckline knit top": "fitted charcoal graphic tee with a mesh underlayer",
        "fitted button-down shirt": "cropped black moto vest over a fitted crimson tank",
        "chiffon blouse with a high-waisted skirt": "distressed steel-gray denim jacket over a black scoop-neck tee",
        "form-fitting dress with classic pumps": "washed-black ribbed top with exposed shoulder seams",
        "leather biker jacket with ripped skinny jeans, combat boots, and layered chains": "black leather biker jacket over a fitted gunmetal camisole",
        "jumpsuit with a dramatic belt": "fitted charcoal band tee under a sleeveless denim vest",
        "tight turtleneck with leather pants": "oxblood distressed-knit top with a wide neckline",
        "belted blazer dress": "black mesh mock-neck top over a fitted crimson camisole",
        "soft sweetheart-neckline knit top": "washed-black asymmetric henley with silver eyelet trim",
    },
    "sleek alternative / industrial": {
        "silk evening gown with a thigh slit": "close-fitting dark-petrol satin evening dress with a sculpted asymmetric neckline",
        "high-waisted leather pants with a silk blouse": "fitted graphite mock-neck top with shoulder cutouts",
        "sleeveless hoodie with cargo joggers and skate shoes": "fitted deep-petrol square-neck bodysuit with gunmetal shoulder hardware",
        "leather mini skirt with an oversized punk sweater and combat boots": "fitted dark-teal zip-front top",
        "fitted leather jacket with dark skinny jeans and ankle boots": "black high-neck top with a sheer decolletage panel",
        "soft linen button-up shirt": "silver-gray halter top with minimalist hardware",
        "faux-leather leggings with an oversized rock band shirt": "fitted steel-blue wrap top with an angular neckline",
        "casual ribbed scoop-neck top": "charcoal corset-seamed top under a fitted black blazer worn open",
        "graphic T-shirt tied at the waist with leather shorts": "fitted gunmetal square-neck top with clean tailoring",
        "studded leather jacket with skinny jeans and heavy boots": "monochrome black knit top with sculptural shoulders",
        "sleeveless mock-neck top with slim jeans": "fitted steel-blue top with a diagonal neckline",
        "casual fitted crew-neck knit top": "tailored charcoal blazer over a satin black camisole",
        "off-shoulder knit dress with ankle boots": "close-fitting steel-blue knit dress with an off-the-shoulder geometric neckline",
        "beaded evening dress with elegant heels": "dark-olive structured blouse with an asymmetric collar",
        "velvet cocktail dress with accessories": "close-fitting electric-violet velvet cocktail dress with a diagonal neckline",
        "fine-knit fitted turtleneck": "black architectural blouse with a sharp open collar",
        "fitted long-sleeve bateau-neck jersey top": "gunmetal fitted top with a collarbone cutout",
        "satin slip dress under an oversized leather jacket": "black zip-front bodysuit under a charcoal structured jacket",
        "double-breasted blazer with wide-leg trousers": "fitted steel-gray top with offset shoulder construction",
        "cropped cardigan over a flowing midi dress": "matte-black corset-seamed top with a square neckline",
        "long wool coat over a turtleneck sweater dress": "graphite satin shell beneath a sharp black vest",
        "knit dress with opaque tights": "fitted petrol-blue knit dress with geometric paneling and a square neckline",
        "puff-sleeve blouse with slim trousers": "fitted electric-violet velvet top with an asymmetric neckline and a shoulder cutout",
    },
    "tailored sexy": {
        "ribbed knit midi dress": "fitted deep-navy blazer worn open over a close-fitting champagne satin square-neck top",
        "casual romper with a thin belt and sneakers": "fitted ivory blouse with the top buttons open",
        "hoodie over a pleated tennis skirt": "fitted cropped camel blazer worn open over a deep-plum sweetheart-neck top",
        "tuxedo blazer over a satin camisole and tailored trousers": "fitted charcoal tuxedo jacket worn open over a close-fitting deep-plum square-neck bodysuit",
        "simple crossover jersey top": "fitted deep-emerald cropped blazer worn open over an ivory sweetheart-neck bodysuit",
        "casual boat-neck knit top": "fitted white button-down shirt with an open collar",
        "sleeveless square-neck camisole under a lightweight open cardigan": "tailored vest over a fitted satin blouse",
        "off-shoulder knit dress": "deep-navy blazer worn open over a close-fitting low square-neck ivory top",
        "lightweight bomber jacket over a fitted crew-neck tee": "cropped blazer over a fitted bodysuit",
        "tailored shorts with a structured blazer": "fitted burgundy silk blouse under a charcoal blazer",
        "ribbed scoop-neck top with cargo pants": "fitted midnight-blue tuxedo jacket worn open over a close-fitting silver satin cowl-neck shell",
        "cap-sleeve sheath dress": "close-fitting ivory wrap-front sheath dress with structured shoulders",
        "fitted waffle-knit henley top": "fitted cool-white silk blouse beneath a black tailored vest",
        "solid-color linen sundress with narrow shoulder straps": "charcoal blazer over a fitted crimson square-neck top",
        "square-neck midi dress": "close-fitting deep-wine satin square-neck dress beneath a cropped black blazer worn open",
        "satin-trim camisole": "fitted ivory open-collar blouse under a cropped charcoal jacket",
        "fine-knit mock neck with tailored shorts": "midnight-blue tuxedo blazer over a silver satin camisole",
        "fitted cotton button-up blouse": "black fitted vest over a cool-white silk shirt with an open collar",
        "off-shoulder evening gown": "structured oxblood blazer over a black sweetheart-neck bodysuit",
        "cropped tank with flowing palazzo pants": "tailored steel-gray jacket over a fitted petrol-blue top",
        "light floral maxi dress with sandals": "cropped ivory blazer over a black cowl-neck camisole",
        "high-fashion couture gown with a sculptural silhouette": "charcoal pinstripe blazer over a fitted black scoop-neck top",
        "cropped tank with parachute pants and skate shoes": "fitted deep-emerald silk blouse with an open collar",
        "fitted cashmere sweater with a pencil skirt": "black tuxedo vest over a champagne satin shell",
        "professional wrap dress with classic pumps": "fitted cool-white wrap blouse under a deep-navy blazer",
        "oversized vintage band hoodie with fishnets and platform sneakers": "short charcoal tuxedo jacket over a fitted silver-gray bodysuit",
        "off-shoulder knit sweater with slim jeans": "tailored charcoal vest over a dark-wine satin camisole",
    },
    "soft luxe / sensual casual": {
        "loose striped sweater with denim shorts and sneakers": "moss-and-cream fitted off-shoulder striped sweater",
        "soft wrap-style jersey top": "fitted pale-lilac cashmere top with a soft off-the-shoulder neckline",
        "graphic T-shirt with cargo shorts and skate shoes": "fitted ivory lace-trim camisole beneath a petrol-blue silk shirt worn open and tailored close to the body",
        "tailored pantsuit with a silk blouse": "fitted blush scoop-neck knit top",
        "fine-knit cardigan over a modest scoop-neck top": "sage cropped fine-knit cardigan worn open over a warm-cream fitted scoop-neck camisole",
        "pencil skirt with a fitted cashmere sweater": "dusty-rose close-fitting cashmere top with a wide boat neckline",
        "lightweight cropped zip hoodie over a plain camisole": "dusty-rose cropped zip hoodie worn open over a warm-cream close-fitting satin camisole with a low scoop neckline",
        "fitted racerback tank top": "soft-gray cold-shoulder cashmere sweater",
        "silk mermaid gown with crystal jewelry": "fitted dusty-mauve wrap knit top",
        "fitted T-shirt tucked into denim shorts with canvas sneakers": "open ivory cardigan over a fitted champagne camisole",
        "band crop top with ripped mom jeans and chunky sneakers": "fitted cocoa ribbed top with a low rounded neckline",
        "boat-neck sweater with a midi skirt": "soft-silver satin shell beneath a lightweight knit cardigan",
        "long trench coat over a fitted bodysuit": "fitted cream long-sleeve top with a wide neckline",
        "casual cropped crew-neck tee ending at the natural waist": "soft-taupe off-the-shoulder sweater",
        "floral wrap dress with delicate jewelry": "close-fitting rose-beige floral-jacquard wrap dress with a softly draped neckline",
        "blazer over a fitted pencil dress": "open charcoal shirt over a fitted ivory tank",
        "loose sweatshirt with relaxed-fit jeans": "pale-lilac silk camisole beneath a soft-gray open cardigan",
        "oversized flannel over a tank with loose jeans": "soft pearl-gray silk wrap top with a gathered shoulder",
        "soft pullover hoodie": "soft charcoal wrap cardigan over a fitted silver satin shell",
        "casual athletic scoop-neck top": "fitted blush cashmere top with a wide boat neckline",
        "lace blouse with tailored shorts": "ivory silk blouse with a softly gathered scoop neckline",
        "lightweight athletic quarter-zip top": "fitted pale-teal fine-knit top with a subtle collarbone cutout",
    },
    "statement / editorial": {
        "sparkling sequined gown": "close-fitting sparkling deep-plum sequined cocktail dress with a sculpted sweetheart neckline",
        "fitted cotton tank top": "silver chainmail-inspired halter top",
        "casual henley-style knit top": "close-fitting metallic-plum satin top with an asymmetric gathered neckline",
        "oversized flannel over a fitted tank with shorts": "electric-violet velvet one-shoulder top",
        "fashion-forward metallic evening suit": "brushed-bronze close-fitting metallic one-shoulder cocktail dress",
        "denim jacket over a fitted tank with skinny jeans": "black sheer tulle top over an opaque sweetheart bodice",
        "fitted pantsuit": "gunmetal sequined cowl-neck top",
        "lace cocktail dress with a delicate necklace": "close-fitting cool-white lace cocktail dress with an illusion sweetheart neckline",
        "lace camisole with leather pants and heeled boots": "deep-emerald satin top with sculptural shoulders",
        "satin wrap gown with an open back and minimalist jewelry": "black organza blouse with a translucent structured collar",
        "tailored tuxedo-inspired suit with heels": "fitted metallic-plum evening top",
        "fitted wrap dress": "sleek ivory draped evening blouse",
        "lightweight romper with woven sandals": "fitted black couture-inspired top with strong shoulder detailing",
        "casual soft boat-neck knit top": "silver organza top with an asymmetric folded neckline",
        "casual cropped cardigan over a fitted camisole": "crimson sequined top with a sculpted portrait neckline",
        "plaid mini skirt with fishnet tights, an oversized band T-shirt, and heavy lace-up boots": "gunmetal chainmail-inspired top over a fitted black bodice",
        "sleeveless silk shell with a midi skirt": "electric-violet satin blouse with dramatic gathered shoulders",
        "silk wrap blouse with tailored pants": "cool-white sculptural organza blouse with a sheer collar",
        "rhinestone-studded cocktail dress": "close-fitting midnight-blue velvet cocktail dress with rhinestone-embroidered shoulders",
        "tropical-print wrap dress": "black metallic-knit top with an architectural one-shoulder neckline",
        "cropped hoodie with baggy jeans and classic skate sneakers": "deep-emerald jacquard top with a translucent structured yoke",
    },
}

TIGHTNESS_DIRECTION = "with every visible layer fitted and tailored close to her body"

WARDROBE_PALETTES = {
    key: f"{prompt}, {TIGHTNESS_DIRECTION}"
    for wardrobes in WARDROBE_GROUPS.values()
    for key, prompt in wardrobes.items()
}
WARDROBE_STYLE_GROUPS = {
    key: group
    for group, wardrobes in WARDROBE_GROUPS.items()
    for key in wardrobes
}
